sudo: require
services:
  - docker

before_install:
  - docker build -t alk3mist/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true alk3mist/docker-react npm run test -- --coverage 
