version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      # do not try to map that folder inside of a container
      - /app/node_modules
      # current folder to /app folder in a container
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

